2021-07-19 05:03:14,731 [INFO] root consoleworker.py:434	Log file created
2021-07-19 05:03:14,731 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7f7560e17c10> added
2021-07-19 05:03:14,731 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f7560e5f850> added
2021-07-19 05:03:14,731 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f7560e03a50> added
2021-07-19 05:03:14,731 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-07-19_05-03-14.698017
2021-07-19 05:03:14,731 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-07-19 05:03:14,731 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-07-19 05:03:14,731 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-07-19 05:03:14,731 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-07-19 05:03:14,731 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-07-19 05:03:14,732 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2021-07-19 05:03:14,732 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-07-19 05:03:14,732 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-07-19 05:03:14,732 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-07-19 05:03:14,732 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-07-19 05:03:14,732 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f7560b57c90>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7f7560b581d0>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7f7560b58310>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7f7560b58150>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7f7560b58b50>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7f7560b57910>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x7f7560b57fd0>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7f7560e7fa10>}
2021-07-19 05:03:14,732 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f7560b57c90>
2021-07-19 05:03:14,732 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-07-19 05:03:14,733 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-19_05-03-14.698017/answ_hCZL7M.log
2021-07-19 05:03:14,733 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-19_05-03-14.698017/phout_2SqzFC.log
2021-07-19 05:03:14,733 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-19_05-03-14.698017/phantom_stat_ZLRy_q.log
2021-07-19 05:03:14,733 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-19_05-03-14.698017/phantom_hJPec3.log
2021-07-19 05:03:14,733 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 178.248.237.139:443
2021-07-19 05:03:14,735 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-07-19 05:03:14,735 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('178.248.237.139', 443)), (2, 2, 17, '', ('178.248.237.139', 443)), (2, 3, 0, '', ('178.248.237.139', 443))]
2021-07-19 05:03:14,735 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 178.248.237.139 and port 443
2021-07-19 05:03:19,743 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [178.248.237.139]:443 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2021-07-19 05:03:19,743 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [178.248.237.139]:443
2021-07-19 05:03:19,743 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [178.248.237.139]:443
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [178.248.237.139]:443, use phantom.connection_test=0 to disable it
2021-07-19 05:03:19,743 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 178.248.237.139 and port 443
2021-07-19 05:03:24,748 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [178.248.237.139]:443 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2021-07-19 05:03:24,748 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [178.248.237.139]:443
2021-07-19 05:03:24,748 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [178.248.237.139]:443
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [178.248.237.139]:443, use phantom.connection_test=0 to disable it
2021-07-19 05:03:24,748 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 178.248.237.139 and port 443
2021-07-19 05:03:29,752 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [178.248.237.139]:443 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2021-07-19 05:03:29,752 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [178.248.237.139]:443
2021-07-19 05:03:29,752 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [178.248.237.139]:443
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [178.248.237.139]:443, use phantom.connection_test=0 to disable it
2021-07-19 05:03:29,755 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 178.248.237.139, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-07-19 05:03:29,756 [INFO] root consoleworker.py:269	Trying to clean up
2021-07-19 05:03:29,756 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_LARHR_.lock
2021-07-19 05:03:29,756 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-07-19 05:03:29,756 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-07-19 05:03:29,760 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-07-19 05:03:29,760 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-07-19_05-03-14.698017
2021-07-19 05:03:29,760 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-19_05-03-14.698017/answ_hCZL7M.log to /var/loadtest/logs/2021-07-19_05-03-14.698017/answ_hCZL7M.log
2021-07-19 05:03:29,760 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-19_05-03-14.698017/answ_hCZL7M.log
2021-07-19 05:03:29,760 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-19_05-03-14.698017/phantom_stat_ZLRy_q.log to /var/loadtest/logs/2021-07-19_05-03-14.698017/phantom_stat_ZLRy_q.log
2021-07-19 05:03:29,760 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-19_05-03-14.698017/phantom_stat_ZLRy_q.log
2021-07-19 05:03:29,760 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-07-19_05-03-14.698017/validation_error.yaml
2021-07-19 05:03:29,761 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-07-19 05:03:29,761 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-19_05-03-14.698017/phantom_hJPec3.log to /var/loadtest/logs/2021-07-19_05-03-14.698017/phantom_hJPec3.log
2021-07-19 05:03:29,761 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-19_05-03-14.698017/phantom_hJPec3.log
2021-07-19 05:03:29,761 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-19_05-03-14.698017/phout_2SqzFC.log to /var/loadtest/logs/2021-07-19_05-03-14.698017/phout_2SqzFC.log
2021-07-19 05:03:29,761 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-19_05-03-14.698017/phout_2SqzFC.log
